version: '3.7'
services:
  oracle-server-db:
    network_mode: bridge
    container_name: oracle-server-db
    image: gvenzl/oracle-xe:slim
    ports:
      - 1521:1521
    environment:
      ORACLE_PASSWORD: 'welcome01'
    expose:
      - 1521
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    container_name: backend
    expose:
      - 3333
    ports:
      - 3333:3333
    depends_on:
      - oracle-server-db
    links:
      - oracle-server-db
    restart: unless-stopped