import { MigrationInterface, QueryRunner } from "typeorm";

export class Default1687407087276 implements MigrationInterface {
    name = 'Default1687407087276'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "Tb_UF" ("Codigo_UF" number GENERATED BY DEFAULT AS IDENTITY, "Sigla" varchar2(255) NOT NULL, "Nome_Municipio" varchar2(255) NOT NULL, "Status" number NOT NULL, CONSTRAINT "PK_f68c076ce61ce8ef6885af31464" PRIMARY KEY ("Codigo_UF"))`);
        await queryRunner.query(`CREATE TABLE "Tb_Municipio" ("Codigo_Municipio" number GENERATED BY DEFAULT AS IDENTITY, "Codigo_UF" number NOT NULL, "Nome" varchar2(255) NOT NULL, "Status" number NOT NULL, CONSTRAINT "PK_b4cdf8fe191eee90cb70e5f8aa5" PRIMARY KEY ("Codigo_Municipio"))`);
        await queryRunner.query(`CREATE TABLE "Tb_Bairro" ("Codigo_Bairro" number GENERATED BY DEFAULT AS IDENTITY, "Codigo_Municipio" number NOT NULL, "Nome_Bairro" varchar2(255) NOT NULL, "Status" number NOT NULL, CONSTRAINT "PK_bf4c5fc1ce26bb48770aed3700a" PRIMARY KEY ("Codigo_Bairro"))`);
        await queryRunner.query(`CREATE TABLE "Tb_Endereco" ("Codigo_Endereco" number GENERATED BY DEFAULT AS IDENTITY, "Codigo_Pessoa" number NOT NULL, "Codigo_Bairro" number NOT NULL, "Nome_Rua" varchar2(255) NOT NULL, "Numero" number NOT NULL, "Complemento" varchar2(255), "CEP" varchar2(255) NOT NULL, CONSTRAINT "PK_e5f8d45d8d8e9ea1e5e655e60c7" PRIMARY KEY ("Codigo_Endereco"))`);
        await queryRunner.query(`CREATE TABLE "Tb_Pessoa" ("Codigo_Pessoa" number GENERATED BY DEFAULT AS IDENTITY, "Nome" varchar2(255) NOT NULL, "Sobrenome" varchar2(255) NOT NULL, "Idade" number NOT NULL, "Data_Nasc" date NOT NULL, "Login" varchar2(255) NOT NULL, "Senha" varchar2(255) NOT NULL, "Status" number NOT NULL, CONSTRAINT "PK_d83c3f0b58f0b930c7d83994c4c" PRIMARY KEY ("Codigo_Pessoa"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "Tb_Pessoa"`);
        await queryRunner.query(`DROP TABLE "Tb_Endereco"`);
        await queryRunner.query(`DROP TABLE "Tb_Bairro"`);
        await queryRunner.query(`DROP TABLE "Tb_Municipio"`);
        await queryRunner.query(`DROP TABLE "Tb_UF"`);
    }

}
